/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aborted.tetsts.example

import org.scalatest.BeforeAndAfter
import org.scalatest.funsuite.AnyFunSuite

class IgnoredTest extends AnyFunSuite with BeforeAndAfter {

    test("some test") {

    }

    ignore("ignored test") {

    }
}
